FileUpload/Models/ErrorViewModel.cs
using System;

namespace FileUpload.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FileUpload/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using FileUpload.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FileUpload.Controllers
{
    public class FileUploadController : Controller
    {
        private readonly IFileUploadService _fileUploadService;

        public FileUploadController(IFileUploadService fileUploadService)
        {
            _fileUploadService = fileUploadService;
        }
            [HttpPost("Index")]
            public IActionResult Index(List<IFormFile> postedFiles)
            {
                var uploadedFiles = _fileUploadService.UploadFiles(postedFiles);
                foreach (var uploadedFile in uploadedFiles)
                {
                    ViewBag.Message += $"{uploadedFile} uploaded. {Environment.NewLine}";    
                }
                return View();
            }
        }
}

FileUpload/Controllers/HomeController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FileUpload.Models;

namespace FileUpload.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ViewResult SubmitDetails(string userId, string password)
        {
            if(userId=="user" && password=="password")
                return View();
            throw new ApplicationException("Userid or password is incorrect");
        }
        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

FileUpload/Views/FileUpload/Index.cshtml
@model object

@{
    ViewBag.Title = "FileUpload Results";
    Layout = "_Layout";
}

<b>Results of upload : <br></b>
<b>@Html.Raw(@ViewBag.Message.Replace(Environment.NewLine, "<br/>"))</b>

FileUpload/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "_Layout";
}

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Login</title>
</head>
<body>
<form method="post" enctype="multipart/form-data" asp-controller="Home" asp-action="SubmitDetails">
    <table>
        <tr>
            <td>User ID: </td>
            <td><input type="text" id="txtUserId" name="UserId"/></td>
        </tr>
        <tr>
            <td>Password: </td>
            <td><input type="text" id="txtPassword" name="Password"/></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Submit"/></td>
        </tr>
    </table>
    <hr/>
</form>
</body>
</html>

FileUpload/Views/Home/SubmitDetails.cshtml
@model object

@{
    Layout = "_Layout";
}

<head>
    <meta name="viewport" content="width=device-width"/>
    <title>File upload</title>
</head>

<form method="post" enctype="multipart/form-data" asp-controller="FileUpload" asp-action="Index">
    <div class="form-group">
        <div class="col-md-10">
            <p>Upload the file(s) using this form:</p>
            <input type="file" name="postedFiles" multiple/>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Upload" />
        </div>
    </div>
</form>

FileUpload/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>